variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 1
  DEV_VERSION_ENABLED: "true"

include:
 - project: 'ProtonVPN/Linux/integration/ci-libraries'
   ref: develop
   file: 'develop-pipeline.yml'
